services:
  frontend:
    image: apichayauwu/medic-app:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      API_BASE_URL: http://backend:8080 # Pass backend URL

  backend:
    image: apichayauwu/medic-go-api:latest
    ports:
      - "8080:8080"
    environment:
      GO_ENV: production
